- name: Instalar nano y python
  
  #fijamos localhost
  hosts: localhost
  
  # activamos superuser
  become: yes

  tasks:

    - name: instalar nano
      apt:
        name: nano
        state: present

    - name: instalar python
      apt:
        name: python3
        state: present

